name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
         submodules: 'recursive'

      - name: Build
        run: xcodebuild -workspace OpenEmu.xcworkspace -scheme "OpenEmu" -configuration Release
      - name: Upload Artifacts
        uses: actions/checkout@v3
        with:
          name: openemu
          path: |
            ~/Library/Developer/Xcode/DerivedData
