name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
         submodules: 'recursive'
         
      - name: Build
        run: xcodebuild -workspace OpenEmu.xcworkspace -scheme "OpenEmu + Cores" -configuration Release
        
      - name: Tar files
        run: tar -cvf openemu-product-release.tar ~/Library/Developer/Xcode/DerivedData/OpenEmu-*/Build/Products/Release


      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: openemu
          path: | 
                 openemu-product-release.tar
                 ~/Library/Developer/Xcode/DerivedData/OpenEmu-*/Build/Products/Release/OpenEmu.app
          
