name: Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  macos:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
         submodules: 'recursive'
         
      - name: Build
        run: xcodebuild -workspace OpenEmu.xcworkspace -scheme "OpenEmu + Cores" -configuration Release
        
      - name: Tar files
        run: | 
             tar -cvf openemu-product-release.tar ~/Library/Developer/Xcode/DerivedData/OpenEmu-*/Build/Products/Release
             tar -cvf openemu.tar ~/Library/Developer/Xcode/DerivedData/OpenEmu-*/Build/Products/Release/OpenEmu.app


      - name: Upload Artifacts DerivedData
        uses: actions/upload-artifact@v3
        with:
          name: openemu-product-release-deriveddata
          path: openemu-product-release.tar
          
      - name: Upload Artifact Binary
        uses: actions/upload-artifact@v3
        with:
          name: openemu
          path: openemu.tar
        
          
